name: skincare
description: "Daily skincare"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  cloud_firestore: ^4.15.0
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.0
  firebase_storage: ^11.6.9
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
